### ISSUE TITLE
how to using custom picture?

### ISSUE THREAD

**Issue by hnuzhoulin** [OpenGVLab/DragGAN#101]
when I upload a image,errors:

```
Registering hook for: b256
Traceback (most recent call last):
  File "/home/zhoulin/miniconda3/envs/draggan/lib/python3.7/site-packages/gradio/routes.py", line 444, in run_predict
    event_data=event_data,
  File "/home/zhoulin/miniconda3/envs/draggan/lib/python3.7/site-packages/gradio/blocks.py", line 1347, in process_api
    fn_index, inputs, iterator, request, event_id, event_data
  File "/home/zhoulin/miniconda3/envs/draggan/lib/python3.7/site-packages/gradio/blocks.py", line 1075, in call_function
    fn, *processed_input, limiter=self.limiter
  File "/home/zhoulin/miniconda3/envs/draggan/lib/python3.7/site-packages/anyio/to_thread.py", line 34, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/home/zhoulin/miniconda3/envs/draggan/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/zhoulin/miniconda3/envs/draggan/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/zhoulin/OpenGVLab-DragGAN/draggan/web.py", line 184, in on_image_change
    result = inverse_image(
NameError: name 'inverse_image' is not defined

```

**Comment by hnuzhoulin** [comment]
the same with  https://github.com/OpenGVLab/DragGAN/issues/100   closed
