### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by 2424004764** [OpenGVLab/DragGAN#105]
2023-07-04 17:45:35 Loading networks from "/root/draggan/checkpoints-pkl/ada/afhqcat.pkl"...
2023-07-04 17:45:36 Traceback (most recent call last):
2023-07-04 17:45:36   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2023-07-04 17:45:36     "__main__", mod_spec)
2023-07-04 17:45:36   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
2023-07-04 17:45:36     exec(code, run_globals)
2023-07-04 17:45:36   File "/app/draggan/web.py", line 318, in <module>
2023-07-04 17:45:36     demo = main()
2023-07-04 17:45:36   File "/app/draggan/web.py", line 241, in main
2023-07-04 17:45:36     G = draggan.load_model(utils.get_path(DEFAULT_CKPT), device=device)
2023-07-04 17:45:36   File "/app/draggan/draggan.py", line 38, in load_model
2023-07-04 17:45:36     chkpt = legacy.load_network_pkl(f, force_fp16=fp16)
2023-07-04 17:45:36   File "/app/draggan/stylegan2/legacy.py", line 21, in load_network_pkl
2023-07-04 17:45:36     data = _LegacyUnpickler(f).load()
2023-07-04 17:45:36 _pickle.UnpicklingError: pickle data was truncated

**Comment by 2424004764** [comment]
![image](https://github.com/OpenGVLab/DragGAN/assets/24261680/24626058-de69-4cd5-9a98-f466b7c931fb)

**Comment by Zeqiang-Lai** [comment]
Your checkpoint might be broken. Try to delete and download again
