### ISSUE TITLE
 For further information visit https://errors.pydantic.dev/2.1.2/v/missing

### ISSUE THREAD

**Issue by SYSUykLin** [OpenGVLab/DragGAN#110]
![Uploading 1689154750097.png…]()
  成功运行了，但是在点击选择起始点的时候出现这个问题，我怀疑可能是我浏览器设置的问题？

**Comment by rajdeep1337** [comment]
嘿！我遇到了同样的问题。您找到修复方法了吗？

**Comment by SCUTykLin** [comment]
yes, I find the path: "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64"

And add this to the torch_utils.custom_ops.py._find_compiler_bindir
`def _find_compiler_bindir():
    patterns = [
        'C:/Program Files*/Microsoft Visual Studio/*/Professional/VC/Tools/MSVC/*/bin/Hostx64/x64',
        'C:/Program Files*/Microsoft Visual Studio/*/BuildTools/VC/Tools/MSVC/*/bin/Hostx64/x64',
        'C:/Program Files*/Microsoft Visual Studio/*/Community/VC/Tools/MSVC/*/bin/Hostx64/x64',
        'C:/Program Files*/Microsoft Visual Studio */vc/bin',
        'D:/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64'
    ]
    for pattern in patterns:
        matches = sorted(glob.glob(pattern))
        if len(matches):
            return matches[-1]
    return None`

It may just work at the situation what I met.

**Comment by rumbleFTW** [comment]
我在Linux上。知道如何在 Linux 上做到这一点吗？
该代码在两周前运行良好。但现在我突然遇到了这个问题。 :(

**Comment by zhaoyajie1011** [comment]
(draggan) bogon:DragGAN zhaoyajie$ python gradio_app.py --device mps
Loading networks from "/Users/zhaoyajie/draggan/checkpoints-pkl/ada/afhqcat.pkl"...
Registering hook for: b256
<string>:240: UserWarning: The operator 'aten::lerp.Scalar_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
Registering hook for: b256
Successfully loaded, starting gradio demo
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.




Task exception was never retrieved
future: <Task finished name='wkwpzbk9md_3' coro=<Queue.process_events() done, defined at /Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, None, 20,...ion_hash': 'wkwpzbk9md'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, None, 20,...ion_hash': 'wkwpzbk9md'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
Task exception was never retrieved
future: <Task finished name='wkwpzbk9md_6' coro=<Queue.process_events() done, defined at /Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, 'data:ima...ion_hash': 'wkwpzbk9md'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, 'data:ima...ion_hash': 'wkwpzbk9md'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
Task exception was never retrieved
future: <Task finished name='wkwpzbk9md_9' coro=<Queue.process_events() done, defined at /Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, 1], 'even...ion_hash': 'wkwpzbk9md'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, 1], 'even...ion_hash': 'wkwpzbk9md'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
Task exception was never retrieved
future: <Task finished name='wkwpzbk9md_8' coro=<Queue.process_events() done, defined at /Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['human/stylegan...ion_hash': 'wkwpzbk9md'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['human/stylegan...ion_hash': 'wkwpzbk9md'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
Task exception was never retrieved
future: <Task finished name='wkwpzbk9md_11' coro=<Queue.process_events() done, defined at /Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...ion_hash': 'wkwpzbk9md'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing>
Traceback (most recent call last):
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaoyajie/miniconda3/envs/draggan/lib/python3.11/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...ion_hash': 'wkwpzbk9md'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing

**Comment by hauelp284** [comment]
Hi, I am having the same issue. Has anyone found a fix? I don't understand what the error is. Thanks!

**Comment by WafaAmr** [comment]
Has anyone been able to fix this annoying bug 🤯 on Linux?

**Comment by WafaAmr** [comment]
I finally found the problem 🎉 guys, its the pydantic version that has a breaking change. 
Replace your latest version of pydantic with 

`pip install pydantic==1.10.11`

**Comment by MADM1k33** [comment]
> I finally found the problem 🎉 guys, its the pydantic version that has a breaking change. Replace your latest version of pydantic with
> 
> `pip install pydantic==1.10.11`

Thank you! This works!
